kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-claim-{{ .Release.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
