kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-slave-claim-{{ .Release.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
spec:
{{- if .Values.zones.enabled }}
  selector:
        matchExpressions:
        - key: "failure-domain.beta.kubernetes.io/zone"
          operator: In
          values: [{{ .Values.zones.zoneName }}]
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi