apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vdbench-west
spec:
  serviceName: "vdbench"
  selector:
    matchLabels:
      app: vdbench
  template:
    metadata:
      labels:
        app: vdbench
    spec:
      containers:
      - name: vdbench
        image: jowings/vdbench:0.8.5
        ports:
        - containerPort: 22
          name: vdbench
        volumeMounts:
        - name: workload-data
          mountPath: /datadir1
  volumeClaimTemplates:
  - metadata:
      name: workload-data
      annotations:
        volume.beta.kubernetes.io/storage-class: pure-block
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi