apiVersion: v1
kind: Service
metadata:
  name: vdbench
  labels:
    app: vdbench
spec:
  ports:
  - port: 22
    name: ssh
  clusterIP: None
  selector:
    app: vdbench
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vdbench-west
spec:
  serviceName: "vdbench"
  replicas: 16
  selector:
    matchLabels:
      app: vdbench
  template:
    metadata:
      labels:
        app: vdbench
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "failure-domain.beta.kubernetes.io/zone"
                  operator: In
                  values: ["WEST"]
      containers:
      - name: vdbench-west
        image: jowings/vdbench:0.8.3
        ports:
        - containerPort: 22
          name: vdbench
        volumeMounts:
        - name: workload-data-west
          mountPath: /datadir1
  volumeClaimTemplates:
  - metadata:
      name: workload-data-west
      annotations:
        volume.beta.kubernetes.io/storage-class: pure-block
    spec:
      selector:
        matchExpressions:
        - key: "failure-domain.beta.kubernetes.io/zone"
          operator: In
          values: ["WEST"]
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vdbench-east
spec:
  serviceName: "vdbench"
  replicas: 16
  selector:
    matchLabels:
      app: vdbench
  template:
    metadata:
      labels:
        app: vdbench
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "failure-domain.beta.kubernetes.io/zone"
                  operator: In
                  values: ["EAST"]
      containers:
      - name: vdbench-east
        image: jowings/vdbench:0.8.3
        ports:
        - containerPort: 22
          name: vdbench
        volumeMounts:
        - name: workload-data-east
          mountPath: /datadir1
  volumeClaimTemplates:
  - metadata:
      name: workload-data-east
      annotations:
        volume.beta.kubernetes.io/storage-class: pure-block
    spec:
      selector:
        matchExpressions:
        - key: "failure-domain.beta.kubernetes.io/zone"
          operator: In
          values: ["EAST"]
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi


